### ISSUE TITLE
upon running, seems Kamara is printed twice.

### ISSUE THREAD

**Issue by coshields** [aptmac/dfs-helper#11]
--- (4/4) Formatting the results ---
                    name position team  salary  points
6          Lamar Jackson       QB  BAL    36.0    25.8
14          Alvin Kamara       RB   NO    33.0    19.0
17          Alvin Kamara       RB   NO    32.0    19.0
66          Stefon Diggs       WR  BUF    24.0    16.1
79         Darren Waller       TE   LV    23.0    14.2
258     Courtland Sutton       WR  DEN    14.0    12.1
267     Emmanuel Sanders       WR  BUF    14.0    12.0
275       Michael Carter       RB  NYJ    14.0    12.5
425  San Francisco 49ers      DEF   SF    10.0     6.8
Total used amount of salary cap: 200.0
Projected points: 137.5
--- Completed ---

**Comment by coshields** [comment]
Thats exactly what it is,  the fantasy pros csv had many duplicates listed in it, I guess it just pulled down strange.

Thanks!

**Comment by aptmac** [comment]
Yeah I've noticed a few hiccups sometimes, and I feel like it's more likely to happen when it's earlier in the week.

Thanks for reporting back!
